In [1]:
import os
import numpy as np
import pandas as pd
train_folder = 'Indian'
all_data = []
for folder in os.listdir(train_folder):
    
    label_folder = os.path.join(train_folder, folder)
    onlyfiles = [{'label':folder,'path':os.path.join(label_folder, f)} for f in os.listdir(label_folder) if os.path.isfile(os.path.join(label_folder, f))]
    #print(onlyfiles)
    all_data += onlyfiles
data_df = pd.DataFrame(all_data)
data_df

      label              path
0         R   Indian/R/63.jpg
1         R  Indian/R/823.jpg
2         R  Indian/R/189.jpg
3         R   Indian/R/77.jpg
4         R  Indian/R/837.jpg
...     ...               ...
42740     W    Indian/W/0.jpg
42741     W  Indian/W/806.jpg
42742     W   Indian/W/46.jpg
42743     W  Indian/W/190.jpg
42744     W  Indian/W/184.jpg

[42745 rows x 2 columns]

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
img_width, img_height = 64, 64
batch_size = 128
y_col = 'label'
x_col = 'path'
no_of_classes = len(data_df[y_col].unique())